# Generated by Django 3.2.5 on 2021-07-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subscribe')),
            ],
        ),
    ]
