# Generated by Django 3.2.5 on 2021-07-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readedposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readedposts',
            old_name='subscribe',
            new_name='subscription',
        ),
    ]
