# Generated by Django 3.2.5 on 2021-07-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_readedposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
